### ISSUE TITLE
Confirm doesn't work correctly in Safari

### ISSUE THREAD

**Issue by teodorpk** [erobertson42/bootstrap-modbox#15]
Testing in Safari 15.5 (17613.2.7.1.8)
Confirm always runs the action defined for the cancel button. You can see it in your examples as well: https://erobertson42.github.io/bootstrap-modbox/examples.html#confirm

It always logs: `okButton not clicked` in the console.

Seems to be only Safari problem though, as it works fine in Chrome/FF.

**Comment by erobertson42** [comment]
Thank you for letting me know.  I'll take a look as soon as I get a chance.

**Comment by erobertson42** [comment]
This should now be fixed in [v1.6.1](https://github.com/erobertson42/bootstrap-modbox/releases/tag/v1.6.1).

Please let me know if it works out.

**Comment by teodorpk** [comment]
Confirmed, works fine thanks!
